# Generated by Django 6.0.7 on 2026-10-06 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('land_area_acres', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('gps_lat', models.FloatField(default=22.75)),
                ('gps_lng', models.FloatField(default=77.72)),
                ('crop_type', models.CharField(default='Organic Rice', max_length=100)),
                ('total_budget', models.DecimalField(decimal_places=2, default=150000.0, max_digits=12)),
                ('allocated_subsidy', models.DecimalField(decimal_places=2, default=45000.0, max_digits=12)),
                ('start_date', models.DateField()),
                ('target_completion', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('VERIFICATION', 'Under Verification'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
