# Generated by Django 6.0.7 on 2026-10-06 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IoTSensorDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=150)),
                ('device_type', models.CharField(default='SOIL_MOISTURE', max_length=50)),
                ('current_reading', models.DecimalField(decimal_places=2, default=38.5, max_digits=8)),
                ('unit', models.CharField(default='%', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
