# Generated by Django 6.0.7 on 2026-10-06 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('LABOUR', 'Labour'), ('SEEDS', 'Seeds'), ('FERTILIZER', 'Fertilizer'), ('IRRIGATION', 'Irrigation'), ('MACHINERY', 'Machinery'), ('TRANSPORT', 'Transport'), ('CONSTRUCTION', 'Construction'), ('COCOPEAT', 'Cocopeat'), ('MISC', 'Miscellaneous')], default='MISC', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
                ('vendor_name', models.CharField(blank=True, max_length=150)),
                ('gst_number', models.CharField(blank=True, max_length=30)),
                ('bill_image_url', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACCOUNTS_VERIFIED', 'Verified by Accounts'), ('ADMIN_APPROVED', 'Approved by Admin'), ('PAID', 'Payment Processed & Visible to Farmer'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=30)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
