# Generated by Django 6.0.7 on 2026-10-06 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=150)),
                ('entity', models.CharField(max_length=100)),
                ('record_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=50)),
                ('device_info', models.CharField(default='Mobile PWA / Chrome', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
