# Generated by Django 6.0.7 on 2026-10-06 15:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_date', models.DateField()),
                ('gps_checkin_lat', models.FloatField(default=22.75)),
                ('gps_checkin_lng', models.FloatField(default=77.72)),
                ('work_description', models.TextField()),
                ('labor_count', models.IntegerField(default=1)),
                ('site_expense_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('is_synced', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='projects.farmproject')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_work_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
