# Generated by Django 6.0.7 on 2026-10-06 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('village', models.CharField(max_length=150)),
                ('district', models.CharField(default='Hoshangabad', max_length=150)),
                ('land_acreage', models.DecimalField(decimal_places=2, default=5.0, max_digits=8)),
                ('primary_crop', models.CharField(default='Organic Rice', max_length=100)),
                ('kisan_id', models.CharField(max_length=50, unique=True)),
                ('aadhar_last4', models.CharField(default='1234', max_length=4)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
