# Generated by Django 6.0.7 on 2026-10-06 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMediaDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('DRONE', 'Drone Imagery'), ('DOCUMENT', 'Document')], default='PHOTO', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file_url', models.TextField()),
                ('gps_lat', models.FloatField(default=22.75)),
                ('gps_lng', models.FloatField(default=77.72)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
            ],
        ),
    ]
