# Generated by Django 6.0.7 on 2026-10-06 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVCamera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('camera_name', models.CharField(max_length=150)),
                ('stream_url', models.TextField()),
                ('vendor_name', models.CharField(default='CP PLUS Hikvision', max_length=100)),
                ('status', models.CharField(default='ONLINE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
